// Copyright 2016 Las Venturas Playground. All rights reserved.
// Use of this source code is governed by the MIT license, a copy of which can
// be found in the LICENSE file.

// Offers functionality to map a vehicle's model Id to a value in range of [0, 100]. More popular
// vehicles will be more expensive, while the worse vehicles are at least affordable.
class VehicleValueMap {
    constructor() {
        this.models_ = {
            400 /* Landstalker */      : 14,
            401 /* Bravura */          :  0,
            402 /* Buffalo */          : 55,
            403 /* Linerunner */       : 29,
            404 /* Pereniel */         :  0,
            405 /* Sentinel */         : 10,
            406 /* Dumper */           : -1,
            544 /* Firetruck */        : -1,
            408 /* Trashmaster */      : 29,
            409 /* Stretch */          : 18,
            410 /* Manana */           :  1,
            411 /* Infernus */         : 98,
            412 /* Voodoo */           : 46,
            413 /* Pony */             : 18,
            414 /* Mule */             :  7,
            415 /* Cheetah */          : 86,
            416 /* Ambulance */        : 46,
            417 /* Leviathan */        : -1,
            418 /* Moonbeam */         :  0,
            419 /* Esperanto */        :  0,
            420 /* Taxi */             :  3,
            421 /* Washington */       : 13,
            422 /* Bobcat */           : 14,
            423 /* Mr Whoopee */       : 11,
            424 /* BF Injection */     : 32,
            425 /* Hunter */           : -1,
            426 /* Premier */          :  2,
            427 /* Enforcer */         : 64,
            428 /* Securicar */        : 50,
            429 /* Banshee */          : 54,
            430 /* Predator */         : -1,
            431 /* Bus */              : -1,
            432 /* Rhino */            : -1,
            433 /* Barracks */         : 61,
            434 /* Hotknife */         : 75,
            591 /* Trailer */          : -1,
            436 /* Previon */          :  1,
            437 /* Coach */            : -1,
            438 /* Cabbie */           :  3,
            439 /* Stallion */         :  1,
            440 /* Rumpo */            :  6,
            441 /* RC Bandit */        : -1,
            442 /* Romero */           : 11,
            443 /* Packer */           : 29,
            444 /* Monster */          : 82,
            445 /* Admiral */          :  9,
            446 /* Squalo */           : -1,
            447 /* Seasparrow */       : -1,
            448 /* Pizzaboy */         :  0,
            449 /* Tram */             : -1,
            451 /* Turismo */          : 89,
            452 /* Speeder */          : -1,
            453 /* Reefer */           : -1,
            454 /* Tropic */           : -1,
            455 /* Flatbed */          : 21,
            456 /* Yankee */           : 21,
            457 /* Caddy */            :  0,
            458 /* Solair */           :  3,
            459 /* Berkley's RC Van */ : -1,
            460 /* Skimmer */          : -1,
            461 /* PCJ-600 */          : 46,
            462 /* Faggio */           :  0,
            463 /* Freeway */          : 25,
            464 /* RC Baron */         : -1,
            465 /* RC Raider */        : -1,
            604 /* Glendale */         :  1,
            467 /* Oceanic */          :  0,
            468 /* Sanchez */          : 11,
            469 /* Sparrow */          : -1,
            470 /* Patriot */          : 54,
            471 /* Quad */             : 29,
            472 /* Coastguard */       : -1,
            473 /* Dinghy */           : -1,
            474 /* Hermes */           :  1,
            475 /* Sabre */            : 32,
            476 /* Rustler */          : -1,
            477 /* ZR-350 */           : 30,
            478 /* Walton */           : 21,
            479 /* Regina */           :  1,
            480 /* Comet */            : 54,
            481 /* BMX */              : -1,
            482 /* Burrito */          : 13,
            483 /* Camper */           : 36,
            484 /* Marquis */          : -1,
            485 /* Baggage */          : -1,
            486 /* Dozer */            : -1,
            487 /* Maverick */         : -1,
            488 /* News Chopper */     : -1,
            505 /* Rancher */          : 25,
            490 /* FBI Rancher */      : 25,
            491 /* Virgo */            :  1,
            492 /* Greenwood */        :  2,
            493 /* Jetmax */           : -1,
            494 /* Hotring */          : -1,
            495 /* Sandking */         : 43,
            496 /* Blista Compact */   :  0,
            497 /* Police Maverick */  : -1,
            609 /* Boxville */         : 10,
            499 /* Benson */           :  9,
            500 /* Mesa */             : 11,
            501 /* RC Goblin */        : -1,
            503 /* Hotring Racer */    : 96,
            504 /* Bloodring Banger */ : 25,
            506 /* Super GT */         : 93,
            507 /* Elegant */          :  5,
            508 /* Journey */          : 43,
            509 /* Bike */             : -1,
            510 /* Mountain Bike */    : -1,
            511 /* Beagle */           : -1,
            512 /* Cropdust */         : -1,
            513 /* Stunt */            : -1,
            514 /* Tanker */           : 30,
            515 /* RoadTrain */        : 29,
            516 /* Nebula */           :  3,
            517 /* Majestic */         :  1,
            518 /* Buccaneer */        :  0,
            519 /* Shamal */           : -1,
            520 /* Hydra */            : -1,
            521 /* FCR-900 */          : 29,
            522 /* NRG-500 */          : 64,
            523 /* HPV1000 */          : 46,
            524 /* Cement Truck */     : 29,
            525 /* Tow Truck */        : -1,
            526 /* Fortune */          :  1,
            527 /* Cadrona */          :  0,
            528 /* FBI Truck */        : 64,
            529 /* Willard */          :  7,
            530 /* Forklift */         : 14,
            531 /* Tractor */          : -1,
            532 /* Combine */          : -1,
            533 /* Feltzer */          :  1,
            534 /* Remington */        : 46,
            535 /* Slamvan */          : 46,
            536 /* Blade */            : 46,
            569 /* Freight */          : -1,
            538 /* Streak */           : -1,
            539 /* Vortex */           : -1,
            540 /* Vincent */          :  0,
            541 /* Bullet */           : 82,
            542 /* Clover */           : 46,
            605 /* Sadler */           : 18,
            545 /* Hustler */          :  1,
            546 /* Intruder */         :  2,
            547 /* Primo */            :  0,
            548 /* Cargobob */         : -1,
            549 /* Tampa */            :  1,
            550 /* Sunrise */          :  1,
            551 /* Merit */            :  3,
            552 /* Utility */          : 15,
            553 /* Nevada */           : -1,
            554 /* Yosemite */         : 25,
            555 /* Windsor */          :  1,
            556 /* Monster Truck 1 */  : -1,
            557 /* Monster Truck 2 */  : -1,
            558 /* Uranus */           : 25,
            559 /* Jester */           : 61,
            560 /* Sultan */           : 75,
            561 /* Stratum */          : 18,
            562 /* Elegy */            : 64,
            563 /* Raindance */        : -1,
            564 /* RC Tiger */         : -1,
            565 /* Flash */            : 50,
            566 /* Tahoma */           :  0,
            567 /* Savanna */          : 46,
            568 /* Bandito */          : 21,
            571 /* Kart */             : 64,
            572 /* Mower */            :  0,
            573 /* Duneride */         : 18,
            574 /* Sweeper */          : 11,
            575 /* Broadway */         : 46,
            576 /* Tornado */          : 46,
            577 /* AT-400 */           : -1,
            578 /* DFT-30 */           : -1,
            579 /* Huntley */          : 39,
            580 /* Stafford */         : 89,
            581 /* BF-400 */           : 14,
            582 /* Newsvan */          : 18,
            583 /* Tug */              : -1,
            585 /* Emperor */          :  5,
            586 /* Wayfarer */         : 29,
            587 /* Euros */            : 57,
            588 /* Hotdog */           : 11,
            589 /* Club */             :  0,
            592 /* Andromada */        : -1,
            593 /* Dodo */             : -1,
            594 /* RC Cam */           : -1,
            595 /* Launch */           : -1,
            596 /* LSPD */             : -1,
            597 /* SFPD */             : -1,
            598 /* LVPD */             : -1,
            599 /* Police Ranger */    : 46,
            600 /* Picador */          :  1,
            601 /* S.W.A.T. */         : 43,
            602 /* Alpha */            :  0,
            603 /* Phoenix */          : 43,
            607 /* Luggage Trailer */  : -1,
            608 /* Stair Trailer */    : -1,
            610 /* Farm Plow */        : -1,
            611 /* Utility Trailer */  : -1
        };
    }

    // Queries the value for a vehicle having |modelId|. The returned value will be in range of
    // [0, 100]. Invalid values for the |modelId| will throw an exception.
    query(modelId) {
        if (!this.models_.hasOwnProperty(modelId))
            throw new Error('The vehicle value query uses an invalid model Id: ' + modelId);

        if (this.models_[modelId] === -1)
            throw new Error('The model Id ' + modelId + ' has not yet been assigned a value.');

        return this.models_[modelId];
    }
}

export default VehicleValueMap;
