// Copyright 2006-2015 Las Venturas Playground. All rights reserved.
// Use of this source code is governed by the GPLv2 license, a copy of which can
// be found in the LICENSE file.

// Format in which the vehicle model data is stored in the array below. This is *not* how an enum
// is meant to be used in Las Venturas Playground code, but in absense of structures we'll allow it.
enum VehicleModelInfoEntry { VehicleModelInfoName[18], VehicleModelInfoFlags };

// Information about Grand Theft Auto: San Andreas' vehicle inventory.
new g_vehicleModelInfo[NumberOfVehicleModels][VehicleModelInfoEntry] = {
    /** 400 **/ { "Landstalker",      TransfenderModificationFlag },
    /** 401 **/ { "Bravura",          TransfenderModificationFlag },
    /** 402 **/ { "Buffalo",          TransfenderModificationFlag },
    /** 403 **/ { "Linerunner",       CanHaveTrailerVehicleFlag },
    /** 404 **/ { "Pereniel",         TransfenderModificationFlag },
    /** 405 **/ { "Sentinel",         TransfenderModificationFlag },
    /** 406 **/ { "Dumper",           0 },
    /** 407 **/ { "Firetruck",        0 },
    /** 408 **/ { "Trashmaster",      0 },
    /** 409 **/ { "Stretch",          TransfenderModificationFlag },
    /** 410 **/ { "Manana",           TransfenderModificationFlag },
    /** 411 **/ { "Infernus",         TransfenderModificationFlag },
    /** 412 **/ { "Voodoo",           LocoLowCoModificationFlag },
    /** 413 **/ { "Pony",             0 },
    /** 414 **/ { "Mule",             0 },
    /** 415 **/ { "Cheetah",          TransfenderModificationFlag },
    /** 416 **/ { "Ambulance",        0 },
    /** 417 **/ { "Leviathan",        HelicopterVehicleFlag },
    /** 418 **/ { "Moonbeam",         TransfenderModificationFlag },
    /** 419 **/ { "Esperanto",        TransfenderModificationFlag },
    /** 420 **/ { "Taxi",             TransfenderModificationFlag },
    /** 421 **/ { "Washington",       TransfenderModificationFlag },
    /** 422 **/ { "Bobcat",           TransfenderModificationFlag },
    /** 423 **/ { "Mr Whoopee",       0 },
    /** 424 **/ { "BF Injection",     TransfenderModificationFlag },
    /** 425 **/ { "Hunter",           HelicopterVehicleFlag },
    /** 426 **/ { "Premier",          TransfenderModificationFlag },
    /** 427 **/ { "Enforcer",         0 },
    /** 428 **/ { "Securicar",        0 },
    /** 429 **/ { "Banshee",          TransfenderModificationFlag },
    /** 430 **/ { "Predator",         BoatVehicleFlag },
    /** 431 **/ { "Bus",              BusVehicleFlag },
    /** 432 **/ { "Rhino",            0 },
    /** 433 **/ { "Barracks",         0 },
    /** 434 **/ { "Hotknife",         0 },
    /** 435 **/ { "Trailer",          TrailerVehicleFlag },
    /** 436 **/ { "Previon",          TransfenderModificationFlag },
    /** 437 **/ { "Coach",            BusVehicleFlag },
    /** 438 **/ { "Cabbie",           TransfenderModificationFlag },
    /** 439 **/ { "Stallion",         TransfenderModificationFlag },
    /** 440 **/ { "Rumpo",            0 },
    /** 441 **/ { "RC Bandit",        RemoteControllableVehicleFlag },
    /** 442 **/ { "Romero",           TransfenderModificationFlag },
    /** 443 **/ { "Packer",           0 },
    /** 444 **/ { "Monster Truck",    0 },
    /** 445 **/ { "Admiral",          TransfenderModificationFlag },
    /** 446 **/ { "Squalo",           BoatVehicleFlag },
    /** 447 **/ { "Seasparrow",       HelicopterVehicleFlag },
    /** 448 **/ { "Pizzaboy",         BikeVehicleFlag },
    /** 449 **/ { "Tram",             StaticVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 450 **/ { "Trailer",          TrailerVehicleFlag },
    /** 451 **/ { "Turismo",          TransfenderModificationFlag },
    /** 452 **/ { "Speeder",          BoatVehicleFlag },
    /** 453 **/ { "Reefer",           BoatVehicleFlag },
    /** 454 **/ { "Tropic",           BoatVehicleFlag },
    /** 455 **/ { "Flatbed",          0 },
    /** 456 **/ { "Yankee",           0 },
    /** 457 **/ { "Caddy",            0 },
    /** 458 **/ { "Solair",           TransfenderModificationFlag },
    /** 459 **/ { "Berkley's RC Van", 0 },
    /** 460 **/ { "Skimmer",          AirplaneVehicleFlag },
    /** 461 **/ { "PCJ-600",          BikeVehicleFlag },
    /** 462 **/ { "Faggio",           BikeVehicleFlag },
    /** 463 **/ { "Freeway",          BikeVehicleFlag },
    /** 464 **/ { "RC Baron",         RemoteControllableVehicleFlag },
    /** 465 **/ { "RC Raider",        HelicopterVehicleFlag | RemoteControllableVehicleFlag },
    /** 466 **/ { "Glendale",         TransfenderModificationFlag },
    /** 467 **/ { "Oceanic",          TransfenderModificationFlag },
    /** 468 **/ { "Sanchez",          BikeVehicleFlag },
    /** 469 **/ { "Sparrow",          HelicopterVehicleFlag },
    /** 470 **/ { "Patriot",          0 },
    /** 471 **/ { "Quad",             0 },
    /** 472 **/ { "Coastguard",       BoatVehicleFlag },
    /** 473 **/ { "Dinghy",           BoatVehicleFlag },
    /** 474 **/ { "Hermes",           TransfenderModificationFlag },
    /** 475 **/ { "Sabre",            TransfenderModificationFlag },
    /** 476 **/ { "Rustler",          AirplaneVehicleFlag },
    /** 477 **/ { "ZR-350",           TransfenderModificationFlag },
    /** 478 **/ { "Walton",           TransfenderModificationFlag },
    /** 479 **/ { "Regina",           TransfenderModificationFlag },
    /** 480 **/ { "Comet",            TransfenderModificationFlag },
    /** 481 **/ { "BMX",              BikeVehicleFlag },
    /** 482 **/ { "Burrito",          0 },
    /** 483 **/ { "Camper",           0 },
    /** 484 **/ { "Marquis",          BoatVehicleFlag },
    /** 485 **/ { "Baggage",          CanHaveTrailerVehicleFlag },
    /** 486 **/ { "Dozer",            0 },
    /** 487 **/ { "Maverick",         HelicopterVehicleFlag },
    /** 488 **/ { "News Chopper",     HelicopterVehicleFlag },
    /** 489 **/ { "Rancher",          TransfenderModificationFlag },
    /** 490 **/ { "FBI Rancher",      0 },
    /** 491 **/ { "Virgo",            TransfenderModificationFlag },
    /** 492 **/ { "Greenwood",        TransfenderModificationFlag },
    /** 493 **/ { "Jetmax",           BoatVehicleFlag },
    /** 494 **/ { "Hotring",          0 },
    /** 495 **/ { "Sandking",         0 },
    /** 496 **/ { "Blista Compact",   TransfenderModificationFlag },
    /** 497 **/ { "Police Maverick",  HelicopterVehicleFlag },
    /** 498 **/ { "Boxville",         0 },
    /** 499 **/ { "Benson",           0 },
    /** 500 **/ { "Mesa",             TransfenderModificationFlag },
    /** 501 **/ { "RC Goblin",        HelicopterVehicleFlag | RemoteControllableVehicleFlag },
    /** 502 **/ { "Hotring Racer",    0 },
    /** 503 **/ { "Hotring Racer",    0 },
    /** 504 **/ { "Bloodring Banger", 0 },
    /** 505 **/ { "Rancher",          TransfenderModificationFlag },
    /** 506 **/ { "Super GT",         TransfenderModificationFlag },
    /** 507 **/ { "Elegant",          TransfenderModificationFlag },
    /** 508 **/ { "Journey",          0 },
    /** 509 **/ { "Bike",             BikeVehicleFlag },
    /** 510 **/ { "Mountain Bike",    BikeVehicleFlag },
    /** 511 **/ { "Beagle",           AirplaneVehicleFlag },
    /** 512 **/ { "Cropdust",         AirplaneVehicleFlag },
    /** 513 **/ { "Stunt",            AirplaneVehicleFlag },
    /** 514 **/ { "Tanker",           CanHaveTrailerVehicleFlag },
    /** 515 **/ { "RoadTrain",        CanHaveTrailerVehicleFlag },
    /** 516 **/ { "Nebula",           TransfenderModificationFlag },
    /** 517 **/ { "Majestic",         TransfenderModificationFlag },
    /** 518 **/ { "Buccaneer",        TransfenderModificationFlag },
    /** 519 **/ { "Shamal",           AirplaneVehicleFlag },
    /** 520 **/ { "Hydra",            AirplaneVehicleFlag },
    /** 521 **/ { "FCR-900",          BikeVehicleFlag },
    /** 522 **/ { "NRG-500",          BikeVehicleFlag },
    /** 523 **/ { "HPV1000",          BikeVehicleFlag },
    /** 524 **/ { "Cement Truck",     0 },
    /** 525 **/ { "Tow Truck",        CanHaveTrailerVehicleFlag },
    /** 526 **/ { "Fortune",          TransfenderModificationFlag },
    /** 527 **/ { "Cadrona",          TransfenderModificationFlag },
    /** 528 **/ { "FBI Truck",        0 },
    /** 529 **/ { "Willard",          TransfenderModificationFlag },
    /** 530 **/ { "Forklift",         0 },
    /** 531 **/ { "Tractor",          CanHaveTrailerVehicleFlag },
    /** 532 **/ { "Combine",          0 },
    /** 533 **/ { "Feltzer",          TransfenderModificationFlag },
    /** 534 **/ { "Remington",        LocoLowCoModificationFlag },
    /** 535 **/ { "Slamvan",          LocoLowCoModificationFlag },
    /** 536 **/ { "Blade",            LocoLowCoModificationFlag },
    /** 537 **/ { "Freight",          StaticVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 538 **/ { "Streak",           StaticVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 539 **/ { "Vortex",           0 },
    /** 540 **/ { "Vincent",          TransfenderModificationFlag },
    /** 541 **/ { "Bullet",           TransfenderModificationFlag },
    /** 542 **/ { "Clover",           TransfenderModificationFlag },
    /** 543 **/ { "Sadler",           0 },
    /** 544 **/ { "Firetruck",        0 },
    /** 545 **/ { "Hustler",          TransfenderModificationFlag },
    /** 546 **/ { "Intruder",         TransfenderModificationFlag },
    /** 547 **/ { "Primo",            TransfenderModificationFlag },
    /** 548 **/ { "Cargobob",         HelicopterVehicleFlag },
    /** 549 **/ { "Tampa",            TransfenderModificationFlag },
    /** 550 **/ { "Sunrise",          TransfenderModificationFlag },
    /** 551 **/ { "Merit",            TransfenderModificationFlag },
    /** 552 **/ { "Utility",          0 },
    /** 553 **/ { "Nevada",           AirplaneVehicleFlag },
    /** 554 **/ { "Yosemite",         0 },
    /** 555 **/ { "Windsor",          TransfenderModificationFlag },
    /** 556 **/ { "Monster Truck",    0 },
    /** 557 **/ { "Monster Truck",    0 },
    /** 558 **/ { "Uranus",           WheelArchAngelsModificationFlag },
    /** 559 **/ { "Jester",           WheelArchAngelsModificationFlag },
    /** 560 **/ { "Sultan",           WheelArchAngelsModificationFlag },
    /** 561 **/ { "Stratum",          WheelArchAngelsModificationFlag },
    /** 562 **/ { "Elegy",            WheelArchAngelsModificationFlag },
    /** 563 **/ { "Raindance",        HelicopterVehicleFlag },
    /** 564 **/ { "RC Tiger",         RemoteControllableVehicleFlag },
    /** 565 **/ { "Flash",            WheelArchAngelsModificationFlag },
    /** 566 **/ { "Tahoma",           LocoLowCoModificationFlag },
    /** 567 **/ { "Savanna",          LocoLowCoModificationFlag },
    /** 568 **/ { "Bandito",          0 },
    /** 569 **/ { "Freight",          DisableCreationVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 570 **/ { "Trailer",          DisableCreationVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 571 **/ { "Kart",             0 },
    /** 572 **/ { "Mower",            0 },
    /** 573 **/ { "Duneride",         0 },
    /** 574 **/ { "Sweeper",          0 },
    /** 575 **/ { "Broadway",         TransfenderModificationFlag },
    /** 576 **/ { "Tornado",          LocoLowCoModificationFlag },
    /** 577 **/ { "AT-400",           AirplaneVehicleFlag },
    /** 578 **/ { "DFT-30",           0 },
    /** 579 **/ { "Huntley",          TransfenderModificationFlag },
    /** 580 **/ { "Stafford",         TransfenderModificationFlag },
    /** 581 **/ { "BF-400",           BikeVehicleFlag },
    /** 582 **/ { "Newsvan",          0 },
    /** 583 **/ { "Tug",              CanHaveTrailerVehicleFlag },
    /** 584 **/ { "Trailer",          TrailerVehicleFlag },
    /** 585 **/ { "Emperor",          TransfenderModificationFlag },
    /** 586 **/ { "Wayfarer",         BikeVehicleFlag },
    /** 587 **/ { "Euros",            TransfenderModificationFlag },
    /** 588 **/ { "Hotdog",           0 },
    /** 589 **/ { "Club",             TransfenderModificationFlag },
    /** 590 **/ { "Trailer",          DisableCreationVehicleFlag | DisableNitroInjectionVehicleFlag },
    /** 591 **/ { "Trailer",          TrailerVehicleFlag },
    /** 592 **/ { "Andromada",        AirplaneVehicleFlag },
    /** 593 **/ { "Dodo",             AirplaneVehicleFlag },
    /** 594 **/ { "RC Cam",           RemoteControllableVehicleFlag },
    /** 595 **/ { "Launch",           BoatVehicleFlag },
    /** 596 **/ { "LSPD",             0 },
    /** 597 **/ { "SFPD",             0 },
    /** 598 **/ { "LVPD",             0 },
    /** 599 **/ { "Police Ranger",    0 },
    /** 600 **/ { "Picador",          TransfenderModificationFlag },
    /** 601 **/ { "S.W.A.T. Van",     0 },
    /** 602 **/ { "Alpha",            TransfenderModificationFlag },
    /** 603 **/ { "Phoenix",          TransfenderModificationFlag },
    /** 604 **/ { "Glendale",         0 },
    /** 605 **/ { "Sadler",           0 },
    /** 606 **/ { "Luggage Trailer",  TrailerVehicleFlag },
    /** 607 **/ { "Luggage Trailer",  TrailerVehicleFlag },
    /** 608 **/ { "Stair Trailer",    TrailerVehicleFlag },
    /** 609 **/ { "Boxville",         0 },
    /** 610 **/ { "Farm Plow",        TrailerVehicleFlag },
    /** 611 **/ { "Utility Trailer",  TrailerVehicleFlag }
};

/**
 * The VehicleModelData class will initialize the individual VehicleModel instances with the data
 * they require in order to function well. The data itself is contained in the array above here.
 *
 * @author Russell Krupke <russell@sa-mp.nl>
 */
class VehicleModelData {
    /**
     * Will be invoked on gamemode load to feed the VehicleModel instances with the data as it's
     * contained in the large array above here.
     */
    public __construct() {
        for (new entryId = 0; entryId < NumberOfVehicleModels; ++entryId) {
            VehicleModel(entryId)->initialize(g_vehicleModelInfo[entryId][VehicleModelInfoName],
                g_vehicleModelInfo[entryId][VehicleModelInfoFlags]);
        }
    }
};
